"""
Utilitários do Sistema
Funções auxiliares para formatação, validação e segurança
"""

from utils.formatters import (
    format_currency,
    format_date,
    format_datetime,
    format_number,
    truncate_text,
    mask_pix_code,
    format_phone,
    format_cpf,
    format_card_number,
    sanitize_html,
    escape_markdown,
    generate_random_code,
    format_file_size,
    format_time_ago,
    format_countdown,
    format_percentage,
    pluralize,
)

from utils.validators import (
    validate_email,
    validate_pix_value,
    validate_telegram_id,
    validate_url,
    validate_product_price,
    validate_stock_code,
    validate_username,
    validate_brazilian_phone,
    validate_cpf,
    validate_cnpj,
    validate_pix_key,
    validate_password_strength,
    validate_discount_code,
    validate_category_name,
    validate_product_name,
    is_valid_json,
    is_valid_base64,
    is_valid_hex_color,
)

from utils.security import (
    hash_data,
    verify_hash,
    encrypt_data,
    decrypt_data,
    generate_token,
    validate_token,
    sanitize_input,
    mask_sensitive_data,
    generate_secure_id,
    rate_limit_check,
    validate_signature,
    secure_compare,
    generate_csrf_token,
    validate_csrf_token,
)

__all__ = [
    # Formatters
    "format_currency",
    "format_date",
    "format_datetime",
    "format_number",
    "truncate_text",
    "mask_pix_code",
    "format_phone",
    "format_cpf",
    "format_card_number",
    "sanitize_html",
    "escape_markdown",
    "generate_random_code",
    "format_file_size",
    "format_time_ago",
    "format_countdown",
    "format_percentage",
    "pluralize",
    # Validators
    "validate_email",
    "validate_pix_value",
    "validate_telegram_id",
    "validate_url",
    "validate_product_price",
    "validate_stock_code",
    "validate_username",
    "validate_brazilian_phone",
    "validate_cpf",
    "validate_cnpj",
    "validate_pix_key",
    "validate_password_strength",
    "validate_discount_code",
    "validate_category_name",
    "validate_product_name",
    "is_valid_json",
    "is_valid_base64",
    "is_valid_hex_color",
    # Security
    "hash_data",
    "verify_hash",
    "encrypt_data",
    "decrypt_data",
    "generate_token",
    "validate_token",
    "sanitize_input",
    "mask_sensitive_data",
    "generate_secure_id",
    "rate_limit_check",
    "validate_signature",
    "secure_compare",
    "generate_csrf_token",
    "validate_csrf_token",
]
